/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Gabriel
 */
public class CitaMenu extends javax.swing.JPanel {

    /**
     * Creates new form CitaMenu
     */
    public CitaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        InsCitaButton = new javax.swing.JButton();
        DelCitaButton = new javax.swing.JButton();
        ModCitaButton = new javax.swing.JButton();
        ConsCitaButton = new javax.swing.JButton();
        ConfCitaButton = new javax.swing.JButton();
        CalCitaButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        InsButton.setBackground(new java.awt.Color(19, 23, 25));
        InsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        InsButton.setForeground(new java.awt.Color(177, 177, 177));
        InsButton.setText("Ingresar Cliente");

        setBackground(new java.awt.Color(51, 51, 51));

        BackButton.setBackground(new java.awt.Color(19, 23, 25));
        BackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(177, 177, 177));
        BackButton.setText("Atrás");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        InsCitaButton.setBackground(new java.awt.Color(19, 23, 25));
        InsCitaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        InsCitaButton.setForeground(new java.awt.Color(177, 177, 177));
        InsCitaButton.setText("Ingresar Cita");

        DelCitaButton.setBackground(new java.awt.Color(19, 23, 25));
        DelCitaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DelCitaButton.setForeground(new java.awt.Color(177, 177, 177));
        DelCitaButton.setText("Borrar Cita");

        ModCitaButton.setBackground(new java.awt.Color(19, 23, 25));
        ModCitaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ModCitaButton.setForeground(new java.awt.Color(177, 177, 177));
        ModCitaButton.setText("Modificar Cita");

        ConsCitaButton.setBackground(new java.awt.Color(19, 23, 25));
        ConsCitaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ConsCitaButton.setForeground(new java.awt.Color(177, 177, 177));
        ConsCitaButton.setText("Consultar Cita");

        ConfCitaButton.setBackground(new java.awt.Color(19, 23, 25));
        ConfCitaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ConfCitaButton.setForeground(new java.awt.Color(177, 177, 177));
        ConfCitaButton.setText("Confirmar Cita");

        CalCitaButton1.setBackground(new java.awt.Color(19, 23, 25));
        CalCitaButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CalCitaButton1.setForeground(new java.awt.Color(177, 177, 177));
        CalCitaButton1.setText("Ver Calendario");

        jPanel3.setBackground(new java.awt.Color(29, 29, 29));
        jPanel3.setPreferredSize(new java.awt.Dimension(322, 85));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 222, 222));
        jLabel3.setText("Sección de Citas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConfCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(CalCitaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DelCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfCitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalCitaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainFrame.getInstance().showPage("MainMenu");
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CalCitaButton1;
    private javax.swing.JButton ConfCitaButton;
    private javax.swing.JButton ConsCitaButton;
    private javax.swing.JButton DelCitaButton;
    private javax.swing.JButton InsButton;
    private javax.swing.JButton InsCitaButton;
    private javax.swing.JButton ModCitaButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
