/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import Control.Control;

/**
 *
 * @author Gabriel
 */
public class ClientMenu extends javax.swing.JPanel {

    /**
     * Creates new form ClientMenu
     */

     
    // Crea una instancia de la clase Control
    Control control = Control.getInstance();

    
    public ClientMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteButton = new javax.swing.JButton();
        InsClienteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        DelClienteButton = new javax.swing.JButton();
        ModClienteButton = new javax.swing.JButton();
        ConsClienteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        ClienteButton.setBackground(new java.awt.Color(19, 23, 25));
        ClienteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ClienteButton.setForeground(new java.awt.Color(177, 177, 177));
        ClienteButton.setText("Menú Clientes");

        setBackground(new java.awt.Color(51, 51, 51));

        InsClienteButton.setBackground(new java.awt.Color(19, 23, 25));
        InsClienteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        InsClienteButton.setForeground(new java.awt.Color(177, 177, 177));
        InsClienteButton.setText("Ingresar Cliente");
        InsClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Solicita al usuario que ingrese el nombre, el email y el teléfono
                String nombre = JOptionPane.showInputDialog("Ingrese el nombre del cliente");
                String email = JOptionPane.showInputDialog("Ingrese el email del cliente");
                String telefono = JOptionPane.showInputDialog("Ingrese el teléfono del cliente");
                                    
                // Llama al método crearCliente en la instancia de Control
                String resultado = control.crearCliente(nombre, email, telefono);
                                
                // Muestra el resultado en un cuadro de diálogo
                JOptionPane.showMessageDialog(null, resultado);
            }
        });


        BackButton.setBackground(new java.awt.Color(19, 23, 25));
        BackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(177, 177, 177));
        BackButton.setText("Atrás");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        DelClienteButton.setBackground(new java.awt.Color(19, 23, 25));
        DelClienteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DelClienteButton.setForeground(new java.awt.Color(177, 177, 177));
        DelClienteButton.setText("Borrar Cliente");
        
        DelClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Solicita al usuario que ingrese el email del cliente a borrar
                String email = JOptionPane.showInputDialog("Ingrese el email del cliente a borrar");
            
                // Llama al método borrarCliente en la instancia de Control
                String resultado = control.borrarCliente(email);
            
                // Muestra el resultado en un cuadro de diálogo
                JOptionPane.showMessageDialog(null, resultado);
            }
        });


        ModClienteButton.setBackground(new java.awt.Color(19, 23, 25));
        ModClienteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ModClienteButton.setForeground(new java.awt.Color(177, 177, 177));
        ModClienteButton.setText("Modificar Cliente");
        ModClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Solicita al usuario que ingrese el email del cliente a modificar
                String email = JOptionPane.showInputDialog("Ingrese el email del cliente a modificar");
                
                // Llama al método consultarCliente en la instancia de Control
                String datosCliente = control.consultarCliente(email);
                                
                // Si el cliente no se encuentra, termina la ejecución
                if (datosCliente.equals("Cliente no encontrado")) {
                    JOptionPane.showMessageDialog(null, datosCliente);
                    return;
                }
                                
                // Muestra los datos actuales del cliente
                JOptionPane.showMessageDialog(null, datosCliente);
                                
                // Solicita al usuario que ingrese el nuevo email y el teléfono del cliente
                String newEmail = JOptionPane.showInputDialog("Ingrese el nuevo email del cliente");
                String telefono = JOptionPane.showInputDialog("Ingrese el nuevo teléfono del cliente");
                            
                // Llama al método modificarCliente en la instancia de Control
                String resultado = control.modificarCliente(newEmail, telefono, email);
                            
                // Muestra el resultado en un cuadro de diálogo
                JOptionPane.showMessageDialog(null, resultado);
                
            }
        });

        ConsClienteButton.setBackground(new java.awt.Color(19, 23, 25));
        ConsClienteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ConsClienteButton.setForeground(new java.awt.Color(177, 177, 177));
        ConsClienteButton.setText("Consultar Cliente");
        
        ConsClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Solicita al usuario que ingrese el email del cliente a consultar
                String email = JOptionPane.showInputDialog("Ingrese el email del cliente a consultar");
                
                // Llama al método consultarCliente en la instancia de Control
                String datosCliente = control.consultarCliente(email);
                
                // Muestra los datos del cliente en un cuadro de diálogo
                JOptionPane.showMessageDialog(null, datosCliente);
            }
        });


        jPanel3.setBackground(new java.awt.Color(29, 29, 29));
        jPanel3.setPreferredSize(new java.awt.Dimension(322, 85));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 222, 222));
        jLabel3.setText("Sección de Clientes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InsClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(BackButton)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainFrame.getInstance().showPage("MainMenu");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void InsClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsClienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsClienteButtonActionPerformed

    private void ModClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModClienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModClienteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ClienteButton;
    private javax.swing.JButton ConsClienteButton;
    private javax.swing.JButton DelClienteButton;
    private javax.swing.JButton InsClienteButton;
    private javax.swing.JButton ModClienteButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
