/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import UI.servicio.ServicioOptionPane;

/**
 *
 * @author Gabriel
 */
public class ServicioMenu extends javax.swing.JPanel {

    /**
     * Creates new form ServicioMenu
     */
    public ServicioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        InsServicioButton = new javax.swing.JButton();
        DelServicioButton = new javax.swing.JButton();
        ModServicioButton = new javax.swing.JButton();
        ConsServicioButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(29, 29, 29));
        jPanel3.setPreferredSize(new java.awt.Dimension(322, 85));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 222, 222));
        jLabel3.setText("Sección de Servicios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        BackButton.setBackground(new java.awt.Color(19, 23, 25));
        BackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(177, 177, 177));
        BackButton.setText("Atrás");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        InsServicioButton.setBackground(new java.awt.Color(19, 23, 25));
        InsServicioButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        InsServicioButton.setForeground(new java.awt.Color(177, 177, 177));
        InsServicioButton.setText("Ingresar Servicio");
        InsServicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsServicioButtonActionPerformed(evt);
            }
        });

        DelServicioButton.setBackground(new java.awt.Color(19, 23, 25));
        DelServicioButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DelServicioButton.setForeground(new java.awt.Color(177, 177, 177));
        DelServicioButton.setText("Borrar Servicio");
        DelServicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelServicioButtonActionPerformed(evt);
            }
        });

        ModServicioButton.setBackground(new java.awt.Color(19, 23, 25));
        ModServicioButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ModServicioButton.setForeground(new java.awt.Color(177, 177, 177));
        ModServicioButton.setText("Modificar Servicio");
        ModServicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModServicioButtonActionPerformed(evt);
            }
        });

        ConsServicioButton.setBackground(new java.awt.Color(19, 23, 25));
        ConsServicioButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ConsServicioButton.setForeground(new java.awt.Color(177, 177, 177));
        ConsServicioButton.setText("Consultar Servicio");
        ConsServicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsServicioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(InsServicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DelServicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ConsServicioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(ModServicioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 107, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InsServicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModServicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConsServicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DelServicioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(121, 121, 121)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainFrame.getInstance().showPage("MainMenu");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void InsServicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsServicioButtonActionPerformed
        ServicioOptionPane.insertarServicio();
    }//GEN-LAST:event_InsServicioButtonActionPerformed

    private void ModServicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModServicioButtonActionPerformed
        ServicioOptionPane.modificarServicio();
    }//GEN-LAST:event_ModServicioButtonActionPerformed

    private void DelServicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelServicioButtonActionPerformed
        ServicioOptionPane.borrarServicio();
    }//GEN-LAST:event_DelServicioButtonActionPerformed

    private void ConsServicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsServicioButtonActionPerformed
        ServicioOptionPane.consultarServicio();
    }//GEN-LAST:event_ConsServicioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ConsServicioButton;
    private javax.swing.JButton DelServicioButton;
    private javax.swing.JButton InsServicioButton;
    private javax.swing.JButton ModServicioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
